version: "3.9" 

services:
  imgcmp-app:
    ports:
      - "5051:5051"  # Expose port 5051 for communication with Caddy

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://srgimgcomp.swapinfotech.com:443 --to http://imgcmp-app:5051
    ports:
      - "80:80"  # Expose port 80 for external access
      - "443:443"  # Expose port 443 for HTTPS 
    volumes:
      - caddy:/data
    depends_on:
      - imgcmp-app
volumes:
  caddy: